name: Build/spectron

on: 
  push:

jobs:
  spectron:
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: yarn
        run: yarn install --network-timeout 1000000 # allows to run without network error

      - name: build
        run: yarn build:github
        env:
          REACT_APP_GRAASP_API_HOST: ${{secrets.REACT_APP_GRAASP_API_HOST}}
          REACT_APP_GRAASP_HOST: ${{secrets.REACT_APP_GRAASP_HOST}}

      - name: Run Spectron
        run: xvfb-run --auto-servernum --server-args='-screen 0, 1600x900x24' yarn mocha:action
